FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Test

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/test]

### Test Get [GET]

+ Response 200 (application/json)

        [
            {
                "test": "I just want to test"
            }
        ]

### Test Post [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "name": "Nancy"
        }

+ Response 201 (application/json)

    + Headers

            Location: /name

    + Body

            {
                "name": "Nancy",
                "message": "Awesome person!"
                
            }

+ Request (application/json)

        {
            "name": "Mike"
        }

+ Response 201 (application/json)

    + Headers

            Location: /name

    + Body

            {
                "name": "Mike",
                "message": "Mean person!"
                
            }
            
+ Request (application/json)

        {
            "name": "Helen"
        }

+ Response 201 (application/json)

    + Headers

            Location: /name

    + Body

            {
                "name": "Helen",
                "message": "The BEST OF ALL!"
                
            }